services:
  - type: web
    name: caseflow
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: flask --app app.py db_init && gunicorn -w 2 -b 0.0.0.0:${PORT} app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///caseflow.db
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: GOOGLE_SCOPES
        value: "email profile https://www.googleapis.com/auth/gmail.readonly https://www.googleapis.com/auth/drive.readonly"
      - key: SYNC_INTERVAL_MINUTES
        value: "30"
      - key: SMTP_HOST
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
